server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://serious-postgres:5432/serious_db
    username: root
    password: root
  cache:
    type: simple
  sql:
    init:
      mode: never  #never/always
      continue-on-error: false #エラーがあれば起動を中止する
      
      schema-locations:
        # - classpath:schema.sql
        # - classpath:schema/01_serious_cases.sql

      data-locations:
        # - classpath:data/01_serious_cases.sql

logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG # SQL　読み込みの詳細ログ

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mapper/**/*.xml