/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("org.springframework.boot") version "3.2.5" //SpringBootのプラグイン
    id("io.spring.dependency-management") version "1.1.4" //バージョン管理のプラグイン
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    //コンパイル時と実行時に必要なライブラリ
    implementation("org.springframework.boot:spring-boot-starter-web") //基本セット
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") //DBとのやり取りの簡易化
    implementation("org.springframework.boot:spring-boot-starter-jdbc") //javaからDBに接続
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3")
    implementation("org.postgresql:postgresql")
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf")

    //テスト時にしか見えない
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.junit.jupiter:junit-jupiter")

    compileOnly("org.projectlombok:lombok:1.18.30")
    annotationProcessor("org.projectlombok:lombok:1.18.30")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.graduation.app.App"
    // mainClass.set("com.graduation.app.App") //重大事案ではこの書き方だがデフォは上で、かつ推奨されている
}
